apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  namespace: qa
  labels:
    app: my-app
spec:
  containers:
  - name: my-container
    image: nginx:latest    #
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "200m"
